/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as MoviesNewImport } from './routes/movies/new'
import { Route as MoviesEditImport } from './routes/movies/edit'
import { Route as MoviesIdImport } from './routes/movies/$id'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MoviesNewRoute = MoviesNewImport.update({
  id: '/movies/new',
  path: '/movies/new',
  getParentRoute: () => rootRoute,
} as any)

const MoviesEditRoute = MoviesEditImport.update({
  id: '/movies/edit',
  path: '/movies/edit',
  getParentRoute: () => rootRoute,
} as any)

const MoviesIdRoute = MoviesIdImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdImport
      parentRoute: typeof rootRoute
    }
    '/movies/edit': {
      id: '/movies/edit'
      path: '/movies/edit'
      fullPath: '/movies/edit'
      preLoaderRoute: typeof MoviesEditImport
      parentRoute: typeof rootRoute
    }
    '/movies/new': {
      id: '/movies/new'
      path: '/movies/new'
      fullPath: '/movies/new'
      preLoaderRoute: typeof MoviesNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/movies/$id': typeof MoviesIdRoute
  '/movies/edit': typeof MoviesEditRoute
  '/movies/new': typeof MoviesNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/movies/$id': typeof MoviesIdRoute
  '/movies/edit': typeof MoviesEditRoute
  '/movies/new': typeof MoviesNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/movies/$id': typeof MoviesIdRoute
  '/movies/edit': typeof MoviesEditRoute
  '/movies/new': typeof MoviesNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/movies/$id'
    | '/movies/edit'
    | '/movies/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/movies/$id'
    | '/movies/edit'
    | '/movies/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/movies/$id'
    | '/movies/edit'
    | '/movies/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  MoviesIdRoute: typeof MoviesIdRoute
  MoviesEditRoute: typeof MoviesEditRoute
  MoviesNewRoute: typeof MoviesNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  MoviesIdRoute: MoviesIdRoute,
  MoviesEditRoute: MoviesEditRoute,
  MoviesNewRoute: MoviesNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/register",
        "/movies/$id",
        "/movies/edit",
        "/movies/new"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/movies/$id": {
      "filePath": "movies/$id.tsx"
    },
    "/movies/edit": {
      "filePath": "movies/edit.tsx"
    },
    "/movies/new": {
      "filePath": "movies/new.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
